# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a5lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/a5lte/proprietary/vendor/bin/hw/vendor.samsung.hardware.nfc@1.0-service:/system/vendor/bin/hw/vendor.samsung.hardware.nfc@1.0-service \
    vendor/samsung/a5lte/proprietary/vendor/lib/hw/nfc_nci.default.so:/system/vendor/lib/hw/nfc_nci.msm8916.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/hw/sensors.vendor.msm8916.so:/system/vendor/lib/hw/sensors.vendor.msm8916.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/hw/vendor.samsung.hardware.nfc@1.0-impl.so:/system/vendor/lib/hw/vendor.samsung.hardware.nfc@1.0-impl.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/vendor.samsung.hardware.nfc@1.0.so:/system/vendor/lib/vendor.samsung.hardware.nfc@1.0.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libalgobsx.so:/system/vendor/lib/libalgobsx.so \
    vendor/samsung/a5lte/proprietary/vendor/etc/nfc/sec_s3fwrn5_rfreg.bin:/system/vendor/etc/nfc/sec_s3fwrn5_rfreg.bin \
    vendor/samsung/a5lte/proprietary/vendor/firmware/nfc/sec_s3fwrn5_firmware.bin:/system/vendor/firmware/nfc/sec_s3fwrn5_firmware.bin \
    vendor/samsung/a5lte/proprietary/vendor/lib/libtfa9895.so:system/lib/libtfa9895.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libsec-ril-dsds.so:system/vendor/lib/libsec-ril-dsds.so

#    vendor/samsung/a5lte/proprietary/vendor/lib/libsecnativefeature.so:/system/vendor/lib/libsecnativefeature.so \
# A500XX Camera blobs
PRODUCT_COPY_FILES += \
    vendor/samsung/a5lte/proprietary/vendor/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/a5lte/proprietary/vendor/lib/hw/camera.msm8916.so:system/vendor/lib/hw/camera.vendor.msm8916.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqomx_core.so:system/lib/libqomx_core.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libactuator_dw9804_a7_camcorder.so:system/vendor/lib/libactuator_dw9804_a7_camcorder.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libactuator_dw9804_a7_camera.so:system/vendor/lib/libactuator_dw9804_a7_camera.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libsecjpeginterface.so:system/lib/libsecjpeginterface.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_dw_dw9806b_eeprom.so:system/vendor/lib/libmmcamera_dw_dw9806b_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_dw_dw9807_eeprom.so:system/vendor/lib/libmmcamera_dw_dw9807_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_imx135.so:system/vendor/lib/libmmcamera_imx135.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so:system/vendor/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_m24128s_eeprom.so:system/vendor/lib/m24128s_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_pdaf.so:system/vendor/lib/libmmcamera_pdaf.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_pdafcamif.so:system/vendor/lib/libmmcamera_pdafcamif.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_rohm_brce064gwz_eeprom.so:system/vendor/lib/libmmcamera_rohm_brce064gwz_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:system/vendor/lib/libmmcamera_s5k5e3yx.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_silicon_sr552_eeprom.so:system/vendor/lib/libmmcamera_silicon_sr552_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_silicon_sr544_eeprom.so:system/vendor/lib/libmmcamera_silicon_sr544_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:system/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:system/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_zc533_eeprom.so:system/vendor/lib/libmmcamera_zc533_eeprom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_common.so:system/lib/libchromatix_imx135_common.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_common_1080p_b.so:system/lib/libchromatix_imx135_common_1080p_b.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_common_1080p_s.so:system/lib/libchromatix_imx135_common_1080p_s.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_common_res0.so:system/lib/libchromatix_imx135_common_res0.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_common_res1.so:system/lib/libchromatix_imx135_common_res1.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_common_res2.so:system/lib/libchromatix_imx135_common_res2.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_common_res3.so:system/lib/libchromatix_imx135_common_res3.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/lib/libchromatix_imx135_default_video.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_golfshot.so:system/lib/libchromatix_imx135_golfshot.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/lib/libchromatix_imx135_hfr_120.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_hfr_1080p_b.so:system/lib/libchromatix_imx135_hfr_1080p_b.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_hfr_1080p_s.so:system/lib/libchromatix_imx135_hfr_1080p_s.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_liveshot.so:system/lib/libchromatix_imx135_liveshot.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_lowres_zslshot.so:system/lib/libchromatix_imx135_lowres_zslshot.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_panorama.so:system/lib/libchromatix_imx135_panorama.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_pip.so:system/lib/libchromatix_imx135_pip.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/lib/libchromatix_imx135_preview.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/lib/libchromatix_imx135_snapshot.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_uhd_video.so:system/lib/libchromatix_imx135_uhd_video.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_zslshot.so:system/lib/libchromatix_imx135_zslshot.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/lib/libmmcamera2_stats_algorithm.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_cac2_lib.so:system/lib/libmmcamera_cac2_lib.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libjpega.so:system/lib/libjpega.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libexifa.so:system/lib/libexifa.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_vt.so:system/vendor/lib/libchromatix_imx135_vt.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_imx135_vt_hd.so:system/vendor/lib/libchromatix_imx135_vt_hd.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_common.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_common.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_pip.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_pip.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_preview.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_preview.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_snapshot.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_snapshot.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_video.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_video.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_vt.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt_hd.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_vt_hd.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_zslshot.so:system/vendor/lib/libchromatix_s5k5e3yx_wide_zslshot.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libAl_Awb.so:system/lib/libAl_Awb.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libAl_Awb_Sp.so:system/lib/libAl_Awb_Sp.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libaf_algo_rear.so:system/lib/libaf_algo_rear.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libaec_algo_front.so:system/lib/libaec_algo_front.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libawb_algo_rear_al.so:system/lib/libawb_algo_rear_al.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libawb_algo_front_al.so:system/lib/libawb_algo_front_al.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libaec_algo_rear.so:system/lib/libaec_algo_rear.so \
    vendor/samsung/a5lte/proprietary/vendor/etc/firmware/cpp_firmware_v1_1_1.fw:system/etc/firmware/cpp_firmware_v1_1_1.fw \
    vendor/samsung/a5lte/proprietary/vendor/etc/firmware/cpp_firmware_v1_1_6.fw:system/etc/firmware/cpp_firmware_v1_1_6.fw \
    vendor/samsung/a5lte/proprietary/vendor/etc/firmware/cpp_firmware_v1_2_0.fw:system/etc/firmware/cpp_firmware_v1_2_0.fw \
    vendor/samsung/a5lte/proprietary/vendor/etc/firmware/cpp_firmware_v1_4_0.fw:system/etc/firmware/cpp_firmware_v1_4_0.fw \
    vendor/samsung/a5lte/proprietary/vendor/etc/B05QL_s5k5e3yx_module_info.xml:system/etc/B05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/a5lte/proprietary/vendor/etc/F13QS_imx135_module_info.xml:system/etc/F13QS_imx135_module_info.xml

# Common stuff
PRODUCT_COPY_FILES += \
    vendor/samsung/a5lte/proprietary/vendor/bin/adsprpcd:system/vendor/bin/adsprpcd \
    vendor/samsung/a5lte/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/samsung/a5lte/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/samsung/a5lte/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/samsung/a5lte/proprietary/vendor/bin/qseecomd:system/vendor/bin/qseecomd \
    vendor/samsung/a5lte/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/samsung/a5lte/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/samsung/a5lte/proprietary/vendor/bin/time_daemon:system/vendor/bin/time_daemon \
    vendor/samsung/a5lte/proprietary/vendor/etc/data/dsi_config.xml:system/vendor/etc/data/dsi_config.xml \
    vendor/samsung/a5lte/proprietary/vendor/etc/data/netmgr_config.xml:system/vendor/etc/data/netmgr_config.xml \
    vendor/samsung/a5lte/proprietary/vendor/etc/data/qmi_config.xml:system/vendor/etc/data/qmi_config.xml \
    vendor/samsung/a5lte/proprietary/vendor/etc/permissions/qti_permissions.xml:system/vendor/etc/permissions/qti_permissions.xml \
    vendor/samsung/a5lte/proprietary/vendor/firmware/a300_pfp.fw:system/vendor/firmware/a300_pfp.fw \
    vendor/samsung/a5lte/proprietary/vendor/firmware/a300_pm4.fw:system/vendor/firmware/a300_pm4.fw \
    vendor/samsung/a5lte/proprietary/vendor/firmware/venus.b00:system/vendor/firmware/venus.b00 \
    vendor/samsung/a5lte/proprietary/vendor/firmware/venus.b01:system/vendor/firmware/venus.b01 \
    vendor/samsung/a5lte/proprietary/vendor/firmware/venus.b02:system/vendor/firmware/venus.b02 \
    vendor/samsung/a5lte/proprietary/vendor/firmware/venus.b03:system/vendor/firmware/venus.b03 \
    vendor/samsung/a5lte/proprietary/vendor/firmware/venus.b04:system/vendor/firmware/venus.b04 \
    vendor/samsung/a5lte/proprietary/vendor/firmware/venus.mbn:system/vendor/firmware/venus.mbn \
    vendor/samsung/a5lte/proprietary/vendor/firmware/venus.mdt:system/vendor/firmware/venus.mdt \
    vendor/samsung/a5lte/proprietary/vendor/bin/perfd:system/vendor/bin/perfd \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:system/vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libESXEGL_adreno.so:system/vendor/lib/egl/libESXEGL_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:system/vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:system/vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libQTapGLES.so:system/vendor/lib/egl/libQTapGLES.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libRBEGL_adreno.so:system/vendor/lib/egl/libRBEGL_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:system/vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:system/vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libFlacSwDec.so:system/vendor/lib/libFlacSwDec.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libOmxAacDec.so:system/vendor/lib/libOmxAacDec.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libOmxEvrcDec.so:system/vendor/lib/libOmxEvrcDec.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libOmxQcelp13Dec.so:system/vendor/lib/libOmxQcelp13Dec.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libQSEEComAPI.so:system/vendor/lib/libQSEEComAPI.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libTimeService.so:system/vendor/lib/libTimeService.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libacdb-fts.so:system/vendor/lib/libacdb-fts.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libacdbrtac.so:system/vendor/lib/libacdbrtac.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libadiertac.so:system/vendor/lib/libadiertac.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libaptX_encoder.so:system/vendor/lib/libaptX_encoder.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libaptXHD_encoder.so:system/vendor/lib/libaptXHD_encoder.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libaudcal.so:system/vendor/lib/libaudcal.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libaudioalsa.so:system/vendor/lib/libaudioalsa.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libbtnv.so:system/vendor/lib/libbtnv.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libdisp-aba.so:system/vendor/lib/libdisp-aba.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libdrmfs.so:system/vendor/lib/libdrmfs.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libdrmtime.so:system/vendor/lib/libdrmtime.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libfastcvopt.so:system/vendor/lib/libfastcvopt.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libllvm-glnext.so:system/vendor/lib/libllvm-glnext.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmm-abl-oem.so:system/vendor/lib/libmm-abl-oem.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmm-abl.so:system/vendor/lib/libmm-abl.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmm-als.so:system/vendor/lib/libmm-als.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmm-disp-apis.so:system/vendor/lib/libmm-disp-apis.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libmm-qdcm.so:system/vendor/lib/libmm-qdcm.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libperipheral_client.so:system/vendor/lib/libperipheral_client.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/librpmb.so:system/vendor/lib/librpmb.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libscale.so:system/vendor/lib/libscale.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libssd.so:system/vendor/lib/libssd.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libstlport.so:system/vendor/lib/libstlport.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libthermalclient.so:system/vendor/lib/libthermalclient.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libthermalioctl.so:system/vendor/lib/libthermalioctl.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/soundfx/libqcbassboost.so:system/vendor/lib/soundfx/libqcbassboost.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/soundfx/libqcreverb.so:system/vendor/lib/soundfx/libqcreverb.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/soundfx/libqcvirt.so:system/vendor/lib/soundfx/libqcvirt.so

# Dirac
PRODUCT_COPY_FILES += \
    vendor/samsung/a5lte/proprietary/vendor/etc/diracmobile.config:$(TARGET_COPY_OUT_VENDOR)/etc/diracmobile.config \
    vendor/samsung/a5lte/proprietary/vendor/lib/libDiracAPI_SHARED.so:$(TARGET_COPY_OUT_VENDOR)/lib/libDiracAPI_SHARED.so \
    vendor/samsung/a5lte/proprietary/vendor/lib/soundfx/libdirac.so:$(TARGET_COPY_OUT_VENDOR)/lib/soundfx/libdirac.so

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libloc_ds_api \
    libtime_genoff \
    TimeService
